### ISSUE TITLE
[error]method not found on version 0.9.0

### ISSUE THREAD

**Issue by chinajinwanjun** [Conflux-Chain/js-conflux-sdk#20]
Hi Core Team,

We used latest version 0.9.0, and found **an error of method not found**, while the same code works fine in version 0.8.0. 

Please review the details as following.
```

0x155c464508e7ed1714bd554dab3cf3fe6711be41
{ data:
   { jsonrpc: '2.0',
     id: '15857042720386224694',
     method: 'cfx_getNextNonce',
     params:
      [ '0x155c464508e7ed1714bd554dab3cf3fe6711be41', 'latest_state' ] },
  error: { code: -32601, message: 'Method not found' },
  duration: 2173 }
{ Error: Method not found
    at HttpProvider.call (C:\conflux\0330\test\node_modules\_js-conflux-sdk@0.9.0-alpha@js-conflux-sdk\lib\provider\HttpProvider.js:45:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: -32601 }
```

Here is our deploy.js code.
```
 
const PRIVATE_KEY = '0x67a6688ba402f7c4056d82f8e72a0d0bf2304c1f7f6e771087bbe0bbdda943e0'
 
// const CONTRACT = '';
const { Conflux } = require('js-conflux-sdk');

async function main() {
  const cfx = new Conflux({
    url: 'http://testnet-jsonrpc.conflux-chain.org:12537',
    defaultGasPrice: 100,
    defaultGas: 1000000,
    logger: console,
  });
  const account = cfx.Account(PRIVATE_KEY); // create account instance
  console.log(account.address); 

  // create contract instance
  const contract = cfx.Contract({
    abi: require('./sol/abi.json'),
    code: require('./sol/code.json'),
  });
  // deploy the contract
  const contractinfo = await contract.constructor()

    .sendTransaction({

      from: account,

      gas: 100000000, // if not set gas, will use 'cfx.defaultGas'

    })
    .confirmed();
  console.log(contractinfo.contractCreated);
}
main().catch(e => console.error(e));
```

**Comment by GeekBerry** [comment]
we change some rpc interface in new version full node, and 0.9.0-alpha sdk for new node, which is not public.
current test net is match sdk 0.8.0.

**Comment by resodo** [comment]
@chinajinwanjun Thanks for the feedback. 0.9.0 is for the current master of fullnode, not for the current testnet (which is http://testnet-jsonrpc.conflux-chain.org:12537). For the current testnet,  please use 0.8.0.
